apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cert-manager
  - external-dns
  - ingress-controller
  - nvidia-device-plugin
  - metallb
  - lan-ingress-controller
