apiVersion: v1
kind: Service
metadata:
  name: router
  namespace: utility-system
  labels:
    app.kubernetes.io/name: router-relay
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: router-relay
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
