apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: enschede-lan
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.240-192.168.1.240
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: enschede-lan
  namespace: metallb-system
spec:
  ipAddressPools:
    - enschede-lan
