apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: traefik-lan
  namespace: ingress-lan-system
  labels:
    release: metrics-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
