apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - deployment-enschede-ws.yaml
  - servicemonitor.yaml
  - pdb.yaml
  - vault-secrets-operator-sa.yaml
  - github-app-vss.yaml
