"""Auto-generated index notes under `_index/`.

The curator regenerates these on every pass that promotes at least
one note, so the human browsing the vault in Obsidian sees:

- ``_index/recent.md`` — the 50 most-recently-promoted notes,
  newest first, as a flat wikilink list.
- ``_index/topics/<topic-slug>.md`` — a Map-of-Content per topic,
  grouping every note under ``topics/<slug>/<type>/*.md`` by type.
- ``_index/conflicts.md`` — every note whose supersedes chain is
  longer than 1 hop, or that has an outstanding ``contradicts``
  edge with no resolution.

All three files are regenerated from disk + database state; hand
edits get overwritten. `.gitattributes` in the vault sets
``merge=union`` on ``_index/**`` so concurrent regenerations from
multiple curator passes converge rather than fight.
"""

from __future__ import annotations

import re
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

import structlog

log = structlog.get_logger(__name__)


_FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---", re.DOTALL)
_H1_RE = re.compile(r"^#\s+(.+)$", re.MULTILINE)


@dataclass(frozen=True, slots=True)
class IndexedNote:
    """Light read-only projection of a promoted note for the indexes."""

    id: str
    rel_path: str  # path under the vault root, e.g. "topics/vault/lesson/foo.md"
    type: str  # lesson | decision | note | fact
    scope: str  # topic:<slug> | project:<repo> | agent:<name>
    title: str
    captured_at: str


def load_promoted_notes(clone_dir: Path) -> list[IndexedNote]:
    """Walk every promoted folder and parse minimal frontmatter.

    Skips `_inbox/` entirely (untriaged) and `_index/` (output of
    this module). Anything else under the vault root is fair game.
    Notes whose frontmatter we can't parse are silently dropped —
    they'll get picked up the next time the curator promotes them.
    """

    out: list[IndexedNote] = []
    for path in sorted(clone_dir.rglob("*.md")):
        rel = path.relative_to(clone_dir).as_posix()
        if rel.startswith(("_inbox/", "_index/", ".obsidian/")):
            continue
        try:
            indexed = _parse_indexed_note(path, rel)
        except ValueError:
            log.warning("indexes.unparseable", path=rel)
            continue
        if indexed is not None:
            out.append(indexed)
    return out


def _parse_indexed_note(path: Path, rel: str) -> IndexedNote | None:
    body = path.read_text(encoding="utf-8")
    match = _FRONTMATTER_RE.search(body)
    if not match:
        return None
    meta: dict[str, str] = {}
    for line in match.group(1).splitlines():
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        meta[key.strip()] = value.strip()
    h1 = _H1_RE.search(body)
    title = h1.group(1).strip() if h1 else meta.get("id", "")
    return IndexedNote(
        id=meta.get("id", ""),
        rel_path=rel,
        type=meta.get("type", "note"),
        scope=meta.get("scope", ""),
        title=title,
        captured_at=meta.get("captured_at", ""),
    )


# -------- recent ----------------------------------------------------


def render_recent(notes: Iterable[IndexedNote], limit: int = 50) -> str:
    """Render `_index/recent.md` — newest first by captured_at.

    Falls back to id sort when captured_at is missing or malformed.
    """

    sorted_notes = sorted(
        notes,
        key=lambda n: (n.captured_at or "0000", n.id),
        reverse=True,
    )[:limit]
    lines = [
        "---",
        "id: kb_index_recent",
        "type: note",
        "scope: agent:_shared",
        "source: curator",
        "confidence: 1.0",
        "tags: [_index, generated]",
        "---",
        "",
        "# Recent",
        "",
        "Auto-generated by the knowledge-curator. Edits here get",
        "overwritten on the next pass.",
        "",
    ]
    if not sorted_notes:
        lines.append("_(no promoted notes yet)_")
    else:
        for note in sorted_notes:
            lines.append(f"- [[{note.rel_path}|{note.title}]] · `{note.scope}` · `{note.type}`")
    lines.append("")
    return "\n".join(lines)


# -------- topic MoC -------------------------------------------------


def topics_present(notes: Iterable[IndexedNote]) -> set[str]:
    """Return the set of topic slugs present in the promoted notes."""

    out: set[str] = set()
    for note in notes:
        if note.scope.startswith("topic:"):
            out.add(note.scope.split(":", 1)[1])
    return out


def render_topic_moc(topic_slug: str, notes: Iterable[IndexedNote]) -> str:
    """Render `_index/topics/<topic-slug>.md` — MoC for a single topic."""

    in_topic = [n for n in notes if n.scope == f"topic:{topic_slug}"]
    by_type: dict[str, list[IndexedNote]] = {}
    for note in in_topic:
        by_type.setdefault(note.type, []).append(note)

    lines = [
        "---",
        f"id: kb_index_topic_{topic_slug}",
        "type: note",
        "scope: agent:_shared",
        "source: curator",
        "confidence: 1.0",
        f"tags: [_index, generated, topic, {topic_slug}]",
        "---",
        "",
        f"# Topic: {topic_slug}",
        "",
        f"Auto-generated Map of Content for `topic:{topic_slug}`.",
        "Edits here get overwritten on the next curator pass.",
        "",
    ]
    if not in_topic:
        lines += ["_(no notes yet under this topic)_", ""]
        return "\n".join(lines)

    for note_type in ("decision", "lesson", "fact", "note"):
        rows = sorted(by_type.get(note_type, []), key=lambda n: n.title.lower())
        if not rows:
            continue
        lines.append(f"## {note_type.title()}s")
        lines.append("")
        for note in rows:
            lines.append(f"- [[{note.rel_path}|{note.title}]]")
        lines.append("")
    return "\n".join(lines)


# -------- conflicts -------------------------------------------------


@dataclass(frozen=True, slots=True)
class ConflictEdge:
    """Minimal projection of a `kb_relations` row for the conflicts index."""

    subject_id: str
    predicate: str  # supersedes | contradicts
    object_id: str


def render_conflicts(
    edges: Iterable[ConflictEdge],
    notes: Iterable[IndexedNote],
) -> str:
    """Render `_index/conflicts.md` from a flat list of conflict edges.

    Caller computes the edge list (typically every row in
    `kb_relations` where predicate is `supersedes` or
    `contradicts`). The index groups by predicate and renders
    wikilinks where the matching note exists, raw id otherwise
    (orphan supersedes pointers happen when the older note has
    not been promoted yet).
    """

    by_id = {n.id: n for n in notes if n.id}
    edges_list = list(edges)

    def render_edge(edge: ConflictEdge) -> str:
        subj = _link_or_id(edge.subject_id, by_id)
        obj = _link_or_id(edge.object_id, by_id)
        return f"- {subj} **{edge.predicate}** {obj}"

    supersedes = [e for e in edges_list if e.predicate == "supersedes"]
    contradicts = [e for e in edges_list if e.predicate == "contradicts"]

    lines = [
        "---",
        "id: kb_index_conflicts",
        "type: note",
        "scope: agent:_shared",
        "source: curator",
        "confidence: 1.0",
        "tags: [_index, generated, conflicts]",
        "---",
        "",
        "# Conflicts",
        "",
        "Auto-generated overlay of `kb_relations` rows that need",
        "human attention. Resolve by editing the involved notes in",
        "Obsidian (`supersedes` is one-way; `contradicts` is",
        "symmetric and usually flags two notes both worth keeping).",
        "",
    ]
    if not edges_list:
        lines += ["_(no outstanding conflicts)_", ""]
        return "\n".join(lines)
    if supersedes:
        lines += ["## Supersedes", ""] + [render_edge(e) for e in supersedes] + [""]
    if contradicts:
        lines += ["## Contradicts", ""] + [render_edge(e) for e in contradicts] + [""]
    return "\n".join(lines)


def _link_or_id(note_id: str, by_id: dict[str, IndexedNote]) -> str:
    note = by_id.get(note_id)
    if note is None:
        return f"`{note_id}`"
    return f"[[{note.rel_path}|{note.title}]]"


# -------- file writers ---------------------------------------------


def write_recent(clone_dir: Path, notes: Iterable[IndexedNote]) -> Path:
    return _write(clone_dir / "_index" / "recent.md", render_recent(notes))


def write_topic_mocs(clone_dir: Path, notes: list[IndexedNote]) -> list[Path]:
    """One MoC per topic slug that's actually in use."""

    out: list[Path] = []
    for slug in sorted(topics_present(notes)):
        out.append(
            _write(
                clone_dir / "_index" / "topics" / f"{slug}.md",
                render_topic_moc(slug, notes),
            )
        )
    return out


def write_conflicts(
    clone_dir: Path,
    edges: Iterable[ConflictEdge],
    notes: Iterable[IndexedNote],
) -> Path:
    return _write(clone_dir / "_index" / "conflicts.md", render_conflicts(edges, notes))


def _write(path: Path, content: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path
