[global]
   workgroup = WORKGROUP
   server string = personal-stack-home
   security = user
   map to guest = Bad User
   log file = /var/log/samba/log.%m
   max log size = 1000
   logging = file
   server role = standalone server
   vfs objects = fruit streams_xattr
   fruit:metadata = stream
   fruit:model = MacSamba
   fruit:posix_rename = yes
   fruit:veto_appledouble = no
   fruit:nfs_aces = no
   fruit:wipe_intentionally_left_blank_rfork = yes
   fruit:delete_empty_adfiles = yes

[films]
   comment = Films
   path = /mnt/media/Films
   browseable = yes
   read only = yes
   guest ok = yes

[series]
   comment = Series
   path = /mnt/media/Series
   browseable = yes
   read only = yes
   guest ok = yes

[anime]
   comment = Anime
   path = /mnt/media/Anime
   browseable = yes
   read only = yes
   guest ok = yes

[databeast]
   comment = Data Beast Storage (full disk)
   path = /mnt/media
   browseable = yes
   read only = no
   write list = media
   valid users = media
   force user = extratoast
   force group = extratoast
   create mask = 0664
   directory mask = 0775

[timemachine]
   comment = Time Machine Backup
   path = /mnt/media/TimeMachine
   browseable = yes
   read only = no
   valid users = media
   force user = extratoast
   force group = extratoast
   vfs objects = fruit streams_xattr
   fruit:time machine = yes
   fruit:time machine max size = 300G
