apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: wolfmanager-db
  namespace: utility-system
spec:
  vaultAuthRef: vso-system/default
  type: kv-v2
  mount: secret
  path: platform/postgres
  destination:
    name: wolfmanager-db
    create: true
    transformation:
      templates:
        DATABASE_URL:
          text: 'postgresql://{{- get .Secrets "wolfmanager.user" -}}:{{- get .Secrets "wolfmanager.password" -}}@postgres.data-system.svc.cluster.local:5432/wolfmanager_db'
  refreshAfter: 1h
  rolloutRestartTargets:
    - kind: Deployment
      name: wolfmanager
