apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secrets-operator
  namespace: utility-system
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: wolfmanager-db
  namespace: utility-system
spec:
  vaultAuthRef: vso-system/default
  mount: database
  path: creds/wolfmanager
  destination:
    name: wolfmanager-db
    create: true
    transformation:
      templates:
        DATABASE_URL:
          text: '{{- printf "postgresql://%s:%s@postgres.data-system.svc.cluster.local:5432/wolfmanager_db" (get .Secrets "username") (get .Secrets "password") -}}'
  rolloutRestartTargets:
    - kind: Deployment
      name: wolfmanager
