#!/usr/bin/env bash
# generate-compose-overlay.sh — Generates a docker-compose.secrets.yml overlay
# that maps versioned Docker Swarm secret names to the expected mount paths.
#
# This overlay is used alongside the main docker-compose.prod.yml:
#   docker stack deploy -c docker-compose.prod.yml -c docker-compose.secrets.yml personal-stack
#
# Usage:
#   source lib/swarm-secrets.sh
#   source lib/generate-compose-overlay.sh
#   generate_compose_overlay /opt/personal-stack/docker-compose.secrets.yml

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source swarm-secrets if not already loaded
if ! declare -f current_secret_ref > /dev/null 2>&1; then
  source "${SCRIPT_DIR}/swarm-secrets.sh"
fi

# All secrets that participate in the versioned rotation scheme.
# Format: "logical_name:services_that_use_it" (comma-separated services)
# The logical name matches both the Docker secret name and the mount path
# inside /run/secrets/.
VERSIONED_SECRETS=(
  "vault_auth_api_role_id"
  "vault_auth_api_secret_id"
  "vault_assistant_api_role_id"
  "vault_assistant_api_secret_id"
  "rabbitmq_user"
  "rabbitmq_password"
  "oauth2_grafana_secret"
  "oauth2_n8n_secret"
  "oauth2_stalwart_secret"
  "grafana_admin_user"
  "grafana_admin_password"
  "stalwart_admin_user"
  "stalwart_admin_password"
  "n8n_db_user"
  "n8n_db_password"
  "postgres_user"
  "postgres_password"
  "auth_db_password"
  "assistant_db_password"
  "cf_dns_api_token"
)

generate_compose_overlay() {
  local output_file="${1:-/opt/personal-stack/docker-compose.secrets.yml}"
  local has_versioned=false

  init_secret_versions

  # Check if any secrets are versioned
  for secret_name in "${VERSIONED_SECRETS[@]}"; do
    local ver
    ver=$(_get_version "$secret_name")
    if [[ "$ver" -gt 0 ]]; then
      has_versioned=true
      break
    fi
  done

  if [[ "$has_versioned" == "false" ]]; then
    # No versioned secrets yet — generate a minimal overlay that changes nothing
    cat > "$output_file" <<'EOF'
# Auto-generated — no versioned secrets active yet.
# All secrets use their base (unversioned) names from docker-compose.prod.yml.
version: "3.8"
EOF
    return 0
  fi

  # Build the overlay
  {
    echo "# Auto-generated by generate-compose-overlay.sh — DO NOT EDIT"
    echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo ""
    echo "secrets:"

    for secret_name in "${VERSIONED_SECRETS[@]}"; do
      local ref
      ref=$(current_secret_ref "$secret_name")
      echo "  ${secret_name}:"
      echo "    name: ${ref}"
      echo "    external: true"
    done
  } > "$output_file"

  chmod 600 "$output_file"
}

# Run if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  generate_compose_overlay "$@"
fi
