apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helm-repositories.yaml
  - metrics-stack
  - grafana
  - loki
  - tempo
  - alloy
  - gatus
  - backup-jobs.yaml
