apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bazarr-lan
  namespace: edge-system
  annotations:
    kubernetes.io/ingress.class: traefik-lan
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: 'Host(`bazarr.jorisjonkers.dev`)'
      services:
        - name: bazarr
          namespace: media-system
          port: 6767
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin-lan
  namespace: edge-system
  annotations:
    kubernetes.io/ingress.class: traefik-lan
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: 'Host(`jellyfin.jorisjonkers.dev`)'
      services:
        - name: jellyfin
          namespace: media-system
          port: 8096
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyseerr-lan
  namespace: edge-system
  annotations:
    kubernetes.io/ingress.class: traefik-lan
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: 'Host(`jellyseerr.jorisjonkers.dev`)'
      services:
        - name: jellyseerr
          namespace: media-system
          port: 5055
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr-lan
  namespace: edge-system
  annotations:
    kubernetes.io/ingress.class: traefik-lan
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: 'Host(`prowlarr.jorisjonkers.dev`)'
      services:
        - name: prowlarr
          namespace: media-system
          port: 9696
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent-lan
  namespace: edge-system
  annotations:
    kubernetes.io/ingress.class: traefik-lan
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: 'Host(`qbittorrent.jorisjonkers.dev`)'
      services:
        - name: qbittorrent
          namespace: media-system
          port: 8080
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr-lan
  namespace: edge-system
  annotations:
    kubernetes.io/ingress.class: traefik-lan
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: 'Host(`radarr.jorisjonkers.dev`)'
      services:
        - name: radarr
          namespace: media-system
          port: 7878
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr-lan
  namespace: edge-system
  annotations:
    kubernetes.io/ingress.class: traefik-lan
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: 'Host(`sonarr.jorisjonkers.dev`)'
      services:
        - name: sonarr
          namespace: media-system
          port: 8989
  tls: {}
