apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secrets-operator
  namespace: media-system
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: immich-postgres
  namespace: media-system
spec:
  vaultAuthRef: vso-system/default
  type: kv-v2
  mount: secret
  path: platform/media/immich-postgres
  destination:
    name: immich-postgres
    create: true
    transformation:
      templates:
        POSTGRES_PASSWORD:
          text: '{{- get .Secrets "postgres.password" -}}'
        DB_PASSWORD:
          text: '{{- get .Secrets "postgres.password" -}}'
  refreshAfter: 1h
  rolloutRestartTargets:
    - kind: Deployment
      name: immich-postgres
    - kind: Deployment
      name: immich-server
