#!/usr/bin/env bash
set -euo pipefail

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
repo_root=$(cd -- "$script_dir/../../.." && pwd)

port="${OPENAPI_EXPORT_PORT:-8099}"
endpoint="http://127.0.0.1:${port}/api/v1/api-docs"
output="$repo_root/services/auth-api/openapi.json"
tmp_json=$(mktemp "${TMPDIR:-/tmp}/auth-api-openapi.XXXXXX.json")
log_file=$(mktemp "${TMPDIR:-/tmp}/auth-api-openapi.XXXXXX.log")
gradle_pid=""
gradle_pgid=""

cleanup() {
  if [[ -n "$gradle_pid" ]] && kill -0 "$gradle_pid" 2>/dev/null; then
    if [[ -n "$gradle_pgid" ]]; then
      kill -TERM "-$gradle_pgid" 2>/dev/null || true
    else
      kill -TERM "$gradle_pid" 2>/dev/null || true
    fi
    wait "$gradle_pid" 2>/dev/null || true
  fi
  rm -f "$tmp_json"
}
trap cleanup EXIT

if curl --fail --silent --show-error "$endpoint" >/dev/null 2>&1; then
  echo "Refusing to export: $endpoint already responds before auth-api starts." >&2
  exit 1
fi

cd "$repo_root"
if command -v setsid >/dev/null 2>&1; then
  setsid ./gradlew --no-daemon :services:auth-api:exportOpenApiSpec -Popenapi.export.port="$port" >"$log_file" 2>&1 &
  gradle_pid=$!
  gradle_pgid=$gradle_pid
else
  ./gradlew --no-daemon :services:auth-api:exportOpenApiSpec -Popenapi.export.port="$port" >"$log_file" 2>&1 &
  gradle_pid=$!
fi

deadline=$((SECONDS + ${OPENAPI_EXPORT_TIMEOUT_SECONDS:-120}))
until curl --fail --silent --show-error "$endpoint" --output "$tmp_json"; do
  if ! kill -0 "$gradle_pid" 2>/dev/null; then
    echo "auth-api OpenAPI export task exited before $endpoint became available." >&2
    tail -n 80 "$log_file" >&2 || true
    exit 1
  fi
  if (( SECONDS >= deadline )); then
    echo "Timed out waiting for $endpoint." >&2
    tail -n 80 "$log_file" >&2 || true
    exit 1
  fi
  sleep 2
done

mv "$tmp_json" "$output"
echo "Wrote $output"
echo "Generated by running: ./gradlew :services:auth-api:exportOpenApiSpec"
