apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - rbac.yaml
  - internal-token-vss.yaml
  - controller.yaml
  - worker.yaml
  - network-policy.yaml
