{
 "title": "Roxy-WI Dashboard",
 "description": "Roxy-WI Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Servers",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "roxy_wi_server_total", "legendFormat": "Total servers" },
    { "expr": "roxy_wi_enabled_server_total", "legendFormat": "Enabled servers" },
    { "expr": "roxy_wi_virtual_server_total", "legendFormat": "Virtual servers" }
   ]
  },
  {
   "title": "Services",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "roxy_wi_services_total", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Users",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "roxy_wi_user_by_role", "legendFormat": "{{role}}" }
   ]
  },
  { "title": "Roxy-WI services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Checkers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "targets": [
    { "expr": "roxy_wi_checker_enabled_total", "legendFormat": "Total checkers" },
    {
     "expr": "roxy_wi_service_checker_enabled_total",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Auto start",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "roxy_wi_auto_start_enabled_total",
     "legendFormat": "Total Auto start"
    },
    {
     "expr": "roxy_wi_service_auto_start_enabled_total",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "targets": [
    { "expr": "roxy_wi_metrics_enabled_total", "legendFormat": "Total metrics" },
    {
     "expr": "roxy_wi_service_metrics_enabled_total",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Number of alerts per server",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "roxy_wi_service_checker_alert{level=\"info\"}",
     "legendFormat": "Info alerts {{hostname}}"
    },
    {
     "expr": "roxy_wi_service_checker_alert{level=\"warning\"}",
     "legendFormat": "Warning alerts {{hostname}}"
    }
   ]
  },
  {
   "title": "Total alerts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "roxy_wi_service_checker_alert_total",
     "legendFormat": "{{level}}"
    }
   ]
  }
 ]
}