build:
  maxIssues: 0

complexity:
  CyclomaticComplexMethod:
    active: true
    allowedComplexity: 10
  LongMethod:
    active: true
    allowedLines: 30
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 6
  LargeClass:
    active: true
    threshold: 300
  TooManyFunctions:
    active: true
    allowedFunctionsInFiles: 15
    allowedFunctionsInClasses: 15
    allowedFunctionsInInterfaces: 15
    allowedFunctionsInObjects: 15
    allowedFunctionsInEnums: 15

style:
  ForbiddenComment:
    active: true
    comments:
      - 'TODO'
      - 'FIXME'
    severity: warning
  MagicNumber:
    active: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
    ignorePropertyDeclaration: true
    ignoreAnnotation: true
    ignoreEnums: true
  MaxLineLength:
    active: true
    maxLineLength: 120
  ReturnCount:
    active: true
    max: 3
  UnusedImport:
    active: true
  VarCouldBeVal:
    active: true
  UnnecessaryAbstractClass:
    active: true
  WildcardImport:
    active: true

potentialbugs:
  UnsafeCallOnNullableType:
    active: true

exceptions:
  TooGenericExceptionCaught:
    active: true

naming:
  FunctionNaming:
    active: true
  ClassNaming:
    active: true
  PackageNaming:
    active: true
